repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3' # Use the revision sha / tag you want to point at
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1' # Use the revision sha / tag you want to point at
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2' # Use the revision sha / tag you want to point at
  hooks:
  - id: flake8
    additional_dependencies: [flake8-docstrings]

- repo: https://github.com/psf/black
  rev: '21.12b0' # Use the revision sha / tag you want to point at
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: poetry run pylint api/
    language: system
    types: [ python ]
    require_serial: true
